# secrets.yaml: Stores sensitive information (like database passwords)

apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
  labels:
    app: my-app
type: Opaque
data:
  DB_USERNAME: bXktZGF0YWJhc2UtdXNlcm5hbWU=  # Use `echo -n 'your-username' | base64`
  DB_PASSWORD: bXktc2VjdXJlLXBhc3N3b3Jk   # Use `echo -n 'your-password' | base64`
  JWT_SECRET: c29tZXJhbmRvbXNlY3JldA==     # Replace with actual secrets encoded in base64
